// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2-eP0nCK7hvQBOSThm5lLtv62iglhYQ',
    appId: '1:937642223539:web:80a22b3b689fdb7e118dc6',
    messagingSenderId: '937642223539',
    projectId: 'connections-cherished',
    authDomain: 'connections-cherished.firebaseapp.com',
    storageBucket: 'connections-cherished.firebasestorage.app',
    measurementId: 'G-1MGDHTB62B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Fmkw9IWLe2PcPc_cxZUR7JD59VuV9d0',
    appId: '1:937642223539:android:a2a4d03519953cce118dc6',
    messagingSenderId: '937642223539',
    projectId: 'connections-cherished',
    storageBucket: 'connections-cherished.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrf13P6ZAf7sTU6ASK_ZMc-6USixxK7tM',
    appId: '1:937642223539:ios:c5e1c4dfb865c93d118dc6',
    messagingSenderId: '937642223539',
    projectId: 'connections-cherished',
    storageBucket: 'connections-cherished.firebasestorage.app',
    iosBundleId: 'com.ccherished',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrf13P6ZAf7sTU6ASK_ZMc-6USixxK7tM',
    appId: '1:937642223539:ios:c5e1c4dfb865c93d118dc6',
    messagingSenderId: '937642223539',
    projectId: 'connections-cherished',
    storageBucket: 'connections-cherished.firebasestorage.app',
    iosBundleId: 'com.ccherished',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo2-eP0nCK7hvQBOSThm5lLtv62iglhYQ',
    appId: '1:937642223539:web:5a3c87d5543b71db118dc6',
    messagingSenderId: '937642223539',
    projectId: 'connections-cherished',
    authDomain: 'connections-cherished.firebaseapp.com',
    storageBucket: 'connections-cherished.firebasestorage.app',
    measurementId: 'G-P2612HJCYH',
  );

}