// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdgGBwUNbDi_1COrmXkwNpZ_r0L7hICjM',
    appId: '1:815352262580:web:41aebc16321864530ecce1',
    messagingSenderId: '815352262580',
    projectId: 'cherished-connections',
    authDomain: 'cherished-connections.firebaseapp.com',
    storageBucket: 'cherished-connections.firebasestorage.app',
    measurementId: 'G-LRE3J79GHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEKMhgyyZRsM1brTcjbRBhNu70_NX_uLg',
    appId: '1:815352262580:android:c5dd96f70102889b0ecce1',
    messagingSenderId: '815352262580',
    projectId: 'cherished-connections',
    storageBucket: 'cherished-connections.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD34ZNQmblMhcFgeR4MC-Kj854d2oAyIAM',
    appId: '1:815352262580:ios:4400334621ee37060ecce1',
    messagingSenderId: '815352262580',
    projectId: 'cherished-connections',
    storageBucket: 'cherished-connections.firebasestorage.app',
    iosBundleId: 'com.example.connectionscherished',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD34ZNQmblMhcFgeR4MC-Kj854d2oAyIAM',
    appId: '1:815352262580:ios:4400334621ee37060ecce1',
    messagingSenderId: '815352262580',
    projectId: 'cherished-connections',
    storageBucket: 'cherished-connections.firebasestorage.app',
    iosBundleId: 'com.example.connectionscherished',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCluAERjMdOPerOBFj1YabCL6fmYenrsss',
    appId: '1:815352262580:web:14a4833ddeb0734f0ecce1',
    messagingSenderId: '815352262580',
    projectId: 'cherished-connections',
    authDomain: 'cherished-connections.firebaseapp.com',
    storageBucket: 'cherished-connections.firebasestorage.app',
    measurementId: 'G-49JH9DQDQR',
  );

}